rcc-uchicago/user-guide

docs/midway23/examples/example_job_scripts.md
mkdocs.yml

Added an example for submitting dependent jobs: these are more flexible than cron jobs.

Added an example job script for dependent jobs

---

docs/midway23/midway_job_management.md

Fixed a typo

---

README.md

Some minor edits to the README file for contributing changes and edits

Some edits to README

---

docs/beagle3/beagle3_overview.md
docs/skyway/skyway_overview.md
mkdocs.yml

This PR is to add text to the mentioned doc pages, fixed some url errors in the top-level mkdocs.yml.

Updated the doc pages of Skyway and Beagle3

---

docs/midway23/midway_job_management.md
docs/midway23/software/apps_and_envs/gromacs.md
docs/midway23/software/apps_and_envs/lammps.md
docs/midway23/software/apps_and_envs/namd.md
docs/midway23/software/cmake.md
docs/midway23/software/compilers.md
docs/midway23/software/libraries.md
mkdocs.yml

This PR contains updates to the doc pages of LAMMPS, NAMD and GROMACS (Issue #26): attempt to simplify and standardize them. Also added Compiling to navigation.

Updated software pages

---

docs/midway23/software/compilers.md
docs/midway23/software/libraries.md
mkdocs.yml

adding nvhpc compilers (that support OpenACC for GPU acceleration), and debuggers

Updated compilers and libraries pages

---

docs/FAQ/data_management_faq.md
docs/midway23/midway_connecting.md
docs/midway23/midway_data_storage.md

two relatively minor additions--a note about how login nodes and compute nodes are system specific, and a new faq about what to do when you're over quota (and I link to that from the data storage page)

note about login/compute nodes, and quota

---

docs/midway23/midway_data_storage.md
docs/midway23/midway_getting_started.md
mkdocs.yml

update to getting started + note about folder access + back to main site button

---

docs/FAQ/connecting_faq.md
docs/midway23/midway_connecting.md

update our ssh key authentication policy for consistency

update policy on ssh keys

---

docs/midway23/examples/example_job_scripts.md
docs/midway23/software/apps_and_envs/singularity.md

This PR adds an example of concurrent runs without GNU parallel with a batch job script (ticket 54013)

Added an example of concurrent runs 

---

docs/FAQ/running_jobs_faq.md

This PR addresses the issue #119.

Added solutions to the openssl error with sinteractive

---

docs/midway23/software/apps_and_envs/alphafold.md

This PR updates the alphafold doc page for the 2.3.2 version.

Updated alphafold page

---

docs/slurm-sbatch.md

shows how SUs can be retrieved per job per user

add how SUs can be computed per job

---

docs/software/apps-and-envs/gromacs.md
docs/software/apps-and-envs/lammps.md
docs/software/apps-and-envs/openmm.md
docs/software/index.md
mkdocs.yml

This PR updated the app pages as the title indicated.

Added OpenMM page, updated LAMMPS and GROMACS pages

---

docs/beagle3-overview.md

Accidentally fixed on the globus branch

Fix internal link in beagle3-overview

---

docs/FAQ/accounts-and-allocations.md
docs/FAQ/data-management.md
docs/FAQ/running-jobs.md
docs/FAQ/software.md
docs/mistakes-to-avoid/list.md
docs/slurm-sbatch.md

Fix hyperlinks in FAQ and Mistakes to Avoid sections

Internal link fixes

---

mkdocs.yml

Previous merge attempt threw:
Error: MkDocs encountered an error parsing the configuration file: while parsing a block mapping
in "/home/runner/work/user-guide/user-guide/mkdocs.yml", line 1, column 1
expected <block end>, but found '-'
in "/home/runner/work/user-guide/user-guide/mkdocs.yml", line 90, column 1

Indent line 90 to enable merge

---

docs/software/apps-and-envs/cryosparc.md

Made minor changes to the CryoSPARC landing page

CryoSPARC minor changes

---

docs/slurm/sbatch.md

Added some details for MPI jobs, removed obsolete text, added concurrent launches for parallel processing

Updates to batch jobs

---

docs/software/apps-and-envs/python.md
docs/software/apps-and-envs/singularity.md
docs/software/apps-and-envs/tf-and-torch.md

This PR fixed some typos and updated the jupyter notebook page.

fixed typo in singularity and pytorch pages, updated jupyter notebook page

---

docs/gis/index.md
docs/partitions.md
mkdocs.yml

This PR contains minor fixes and exposes GIS pages to navigation on the left panel.

Minor fixes and expose GIS pages to navigation

---

docs/software/apps-and-envs/python.md

From:
```shell
!/bin/bash # Missing `#`
#SBATCH --job-name=jupyter-launch
#SBATCH --account=pi-[cnetid]
#SBATCH --output=output-%J.txt
#SBATCH --error=error-%J.txt
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --memb=8GB # Typo `--memb`
```
to:
```shell
#!/bin/bash
#SBATCH --job-name=jupyter-launch
#SBATCH --account=pi-[cnetid]
#SBATCH --output=output-%J.txt
#SBATCH --error=error-%J.txt
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=8GB
```

Fix sbatch file example for Python & Jupyter
